#document settings
title: Project Interoperability
desc: "Project Interoperability — Information is a National Asset"
url: http://project-interoperability.github.io/
repo_name: project-interoperability.github.io
branch: master

#global settings, no need to change these
root_url: http://project-interoperability.github.io/
org_name: project-interoperability
prose_url: http://prose.io

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false
